Lizz   dev rhythm 1
vmware-tanzu/tanzu-dev-portal pull request #1171
Opened 2021-08-10 20:39 UTC by lizz7000

2021-08-11 19:11 UTC, billkable approved these changes

2021-08-11 19:17 UTC, billkable requested changes
The foundations *code patterns* section is incorrect.

See the definition updates inline

2021-08-12 14:10 UTC, lizz7000 commented on content/outcomes/application-development-rhythm/foundations.md
> +Code patterns are traceable events that happen when a developer codes.
Thank you, Bill. I'll add that one...

2021-08-12 14:26 UTC, lizz7000 commented on content/outcomes/application-development-rhythm/foundations.md
> +Code patterns are traceable events that happen when a developer codes.
Hi Bill,

I'm still looking at the patterns topic. When you write, "Think of patterns as one of the 
high level *whats* of building software.", it's a little unclear to me what a high level "what" might be. Can you please provide an example in your description? 

Also, can you please provide a "why" to the sentence, *Patterns* are also long-lived, similar to *practices* in the same way that you did when describing the "how" in the Practices section?

2021-08-12 14:35 UTC, lizz7000 commented
Hi Bill,

Please see the following sentence under the Practices section.

"The lifetime of principles is tied to the relevance of the context in which they
live."

I understand what you're saying, but I have to stop and think about it. If you had to describe this as simply as possible, how would you write it?

2021-09-17 20:54 UTC, joemoore commented
Is this pull request still relevant? If not we can close it.

2021-09-17 20:55 UTC, lizz7000 commented
Hi,

It can be closed.

Thanks,

Lizz.
________________________________
From: Joe Moore ***@***.***>
Sent: Friday, September 17, 2021 4:54 PM
To: vmware-tanzu/tanzu-dev-portal ***@***.***>
Cc: Lizz Smullen ***@***.***>; Mention ***@***.***>
Subject: Re: [vmware-tanzu/tanzu-dev-portal] Lizz dev rhythm 1 (#1171)


Is this pull request still relevant? If not we can close it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvmware-tanzu%2Ftanzu-dev-portal%2Fpull%2F1171%23issuecomment-922075527&data=04%7C01%7Clsmullen%40vmware.com%7C647c86210b164d35e96508d97a1d5762%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637675088711339025%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=OZAYLPWvc4JVeMf4DJvcT7Du82yfUeOQn5No8kL1eSM%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAT35X6ERMZ62XG57UHTC5VLUCOTIJANCNFSM5B43FGJQ&data=04%7C01%7Clsmullen%40vmware.com%7C647c86210b164d35e96508d97a1d5762%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637675088711349007%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=IKv2HhVBVDpFwrbJCwFtr%2FY81I3jOIyIHrDo0eKaiHE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Clsmullen%40vmware.com%7C647c86210b164d35e96508d97a1d5762%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637675088711354004%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0yTejLJWcANCbIYr56Mg9rIK0za6EA9fat13goKTIyE%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Clsmullen%40vmware.com%7C647c86210b164d35e96508d97a1d5762%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637675088711358986%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=KF%2FYQcPFzVOvsDJzR%2FQAI0O4ctUpShVojWwB9qCBaUg%3D&reserved=0>.

2021-09-17 21:11 UTC, joemoore commented
closed by request

2021-09-17 21:11 UTC, closed without merging