Updated .NET in the Wild with a new show and reordered following
vmware-tanzu/tanzu-dev-portal pull request #1436
Opened 2021-11-24 11:26 UTC by Layla-P

2021-11-24 14:14 UTC, BrianMMcClain approved these changes

2021-11-24 15:36 UTC, BrianMMcClain requested changes
Hey @Layla-P! I opened a PR against your branch with just a couple additions to the dictionary. Once that's merged, I'll be able to merge this. Thanks!

2021-11-25 19:55 UTC, Layla-P commented
Sorry @BrianMMcClain I forgot about the dictionary! Sorry!!

2021-11-26 01:39 UTC, BrianMMcClain approved these changes

2021-11-26 01:39 UTC, merged