WIP Outcomes: Adding TDD
vmware-tanzu/tanzu-dev-portal pull request #988
Opened 2021-06-22 00:04 UTC by joemoore

2021-06-22 16:52 UTC, jfm-abbott commented on content/outcomes/application-development/test-driven-development.md
> +Integration Tests operate on smaller parts of the system than End-tond Tests, thus running faster. They also test larger parts than unit tests, thus running slower than unit tests.
End-to-End typo

2021-06-22 20:16 UTC, joemoore commented on content/outcomes/application-development/test-driven-development.md
> +Integration Tests operate on smaller parts of the system than End-tond Tests, thus running faster. They also test larger parts than unit tests, thus running slower than unit tests.
```suggestion
Integration Tests operate on smaller parts of the system than End-to-End Tests, thus running faster. They also test larger parts than unit tests, thus running slower than unit tests.
```

2021-06-22 20:16 UTC, joemoore commented on content/outcomes/application-development/test-driven-development.md
> +Integration Tests operate on smaller parts of the system than End-tond Tests, thus running faster. They also test larger parts than unit tests, thus running slower than unit tests.
Thank you!

2021-06-23 16:26 UTC, BrianMMcClain requested changes

2021-06-23 16:26 UTC, BrianMMcClain commented on content/outcomes/application-development/test-driven-development.md
> +*** image of testing pyramid here**
Missing image?

2021-06-23 20:07 UTC, joemoore commented on content/outcomes/application-development/test-driven-development.md
> +*** image of testing pyramid here**
Yes I will add one.

2021-06-23 20:26 UTC, joemoore commented on content/outcomes/application-development/test-driven-development.md
> +*** image of testing pyramid here**
Added

2021-06-24 13:04 UTC, BrianMMcClain approved these changes

2021-06-24 13:41 UTC, merged